server:
  host: "0.0.0.0"
  port: "8000"

backends:
  - "http://localhost:9000"
  - "http://localhost:9001"
  - "http://localhost:9002"

algorithm: "roundrobin"

health_check:
  interval: 30s
  timeout: 5s
  path: "/health"