server:
  host: "0.0.0.0"
  port: 8080

backends:
  - url: "http://localhost:3001"
    weight: 1
  - url: "http://localhost:3002"
    weight: 2
  - url: "http://localhost:3003"
    weight: 1

algorithm: "round_robin"

health_check:
  interval: 30s
  timeout: 5s
  path: "/health"